# Generated by Django 4.0.6 on 2022-07-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers_info',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
