# Generated by Django 4.0.4 on 2022-07-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_alter_studentinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='registration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
