# Generated by Django 4.0.4 on 2022-07-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_studentinfo_registration_alter_studentinfo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='media/img')),
            ],
        ),
    ]
