# Generated by Django 4.0.4 on 2022-07-28 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_teachers_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teachers_info',
        ),
    ]
