# Generated by Django 4.0.6 on 2022-07-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_delete_teachers_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='certificate',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
